# Generated by Django 3.0.7 on 2020-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='main_photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
