# Generated by Django 3.0.7 on 2020-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200626_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Client Name, Project Category, Project date, Project Description', verbose_name='About Project'),
        ),
    ]
