# Generated by Django 3.0.7 on 2020-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200626_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Client Name, Project Category, Project date, Project Description'),
        ),
    ]
