# Generated by Django 3.0.7 on 2020-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200627_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Team'),
        ),
    ]
