# Generated by Django 3.0.7 on 2020-06-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Team'),
        ),
    ]
